# Generated by Django 5.2.17 on 2026-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Defaults to system date at entry time; may be adjusted for a valid historical entry. Never overwritten on edit.')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('decade', models.CharField(choices=[('first', 'Days 1-10'), ('second', 'Days 11-20'), ('third', 'Day 21 to end of month')], max_length=10)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('branch', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposits',
                'ordering': ['-date'],
            },
        ),
    ]
