# Generated by Django 5.2.17 on 2026-09-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='decade',
            field=models.CharField(choices=[('first', 'دهه اول'), ('second', 'دهه دوم'), ('third', 'دهه سوم')], max_length=10),
        ),
    ]
