# Generated by Django 5.2.17 on 2026-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text="First activation date. Starts the license period AND is renewed to 'today' on successful renewal. Does NOT define accounting history start.")),
                ('duration_days', models.PositiveIntegerField(default=365)),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
    ]
