# Generated by Django 5.2.17 on 2026-08-29 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('workday', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_number', models.AutoField(primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('working_day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoice', to='workday.dailyworkingday')),
            ],
            options={
                'verbose_name': 'Sales Invoice',
                'verbose_name_plural': 'Sales Invoices',
            },
        ),
        migrations.CreateModel(
            name='NozzleSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_meter', models.DecimalField(decimal_places=2, max_digits=14)),
                ('new_meter', models.DecimalField(decimal_places=2, max_digits=14)),
                ('test', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sales_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='stations.nozzle')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_sales', to='sales.salesinvoice')),
            ],
            options={
                'verbose_name': 'Nozzle Sale',
                'verbose_name_plural': 'Nozzle Sales',
                'constraints': [models.UniqueConstraint(fields=('nozzle', 'sales_invoice'), name='unique_nozzle_per_sales_invoice')],
            },
        ),
    ]
