# Generated by Django 5.2.17 on 2026-08-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NozzleSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('flag_door_1', 'Flag Door 1'), ('flag_door_2', 'Flag Door 2'), ('pump_door_1', 'Pump Door 1'), ('pump_door_2', 'Pump Door 2')], max_length=20)),
                ('date', models.DateField()),
                ('seal_number', models.CharField(max_length=100)),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seals', to='stations.nozzle')),
            ],
            options={
                'verbose_name': 'Nozzle Seal',
                'verbose_name_plural': 'Nozzle Seals',
                'ordering': ['-date'],
            },
        ),
    ]
