# Generated by Django 5.2.17 on 2026-10-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzleseal',
            name='section',
            field=models.CharField(choices=[('flag_door_1', 'درب پرچمی 1'), ('flag_door_2', 'درب پرچمی 2'), ('pump_door_1', 'درب تلمبه 1'), ('pump_door_2', 'درب تلمبه 2')], max_length=20),
        ),
    ]
