# Generated by Django 5.2.17 on 2026-08-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('complete', 'Complete')], default='incomplete', max_length=20)),
            ],
            options={
                'verbose_name': 'Daily Working Day',
                'verbose_name_plural': 'Daily Working Days',
                'ordering': ['date'],
            },
        ),
    ]
