# Generated by Django 5.2.17 on 2026-10-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='setup_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='setup_locked',
            field=models.BooleanField(default=False),
        ),
    ]
