# Generated by Django 5.2.17 on 2026-08-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('workday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('effective_month', models.DateField(help_text='Day 1 of the first accounting month this opening balance applies to.')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_inventories', to='stations.tank')),
            ],
            options={
                'verbose_name': 'Opening Inventory',
                'verbose_name_plural': 'Opening Inventories',
                'constraints': [models.UniqueConstraint(fields=('tank', 'effective_month'), name='unique_opening_inventory_per_tank_month')],
            },
        ),
        migrations.CreateModel(
            name='TankInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_inventory', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='stations.tank')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_inventories', to='workday.dailyworkingday')),
            ],
            options={
                'verbose_name': 'Tank Inventory',
                'verbose_name_plural': 'Tank Inventories',
                'constraints': [models.UniqueConstraint(fields=('tank', 'working_day'), name='unique_tank_inventory_per_day')],
            },
        ),
    ]
