# Generated by Django 5.2.17 on 2026-08-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('workday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unloading_time', models.TimeField(blank=True, null=True)),
                ('program_number', models.CharField(blank=True, max_length=100)),
                ('tanker_number', models.CharField(blank=True, help_text='Vehicle/license plate. No uniqueness constraint -- operator-owned business identifier.', max_length=100)),
                ('tanker_capacity', models.PositiveIntegerField(blank=True, help_text='Liters. No fixed restriction enforced.', null=True)),
                ('quantity', models.PositiveIntegerField(help_text='Liters (integer quantities only).')),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('document_number', models.CharField(blank=True, help_text='Manually entered by the operator. No uniqueness or duplicate validation is applied; the operator is responsible for correctness.', max_length=100)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='stations.tank')),
                ('working_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='workday.dailyworkingday')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
                'verbose_name_plural': 'Purchase Invoices',
            },
        ),
    ]
